# Site Rex
name: Teach The World to Code
description: Resources and instruction for elementary and secondary computer science education
meta_description: "Coding Instruction Education Elementary Secondary"
logo: 'assets/images/ttwtc-logo-wtext.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl:
email: 'help@TeachTheWorldToCode.org'
google_analytics: 'UA-46278016-1'
disqus: 'teachtheworldtocode'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'
callout_background_color: '#00a9ec'

# Authors
authors:
  rex:
    name: Rex
    display_name: Rex
    gravatar: 431ee30c3efced64c90d50a9165cba79
    email: petersen.rex@gmail.com
    web: http://www.openelastic.com
    twitter: https://twitter.com/OpenElastic
    description: "AWS cloud migration enabler."

#Collections
collections:
  team:
    output: true
    permalink: /:collection/:name
 
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge